### ISSUE TITLE
cant stop afk-state through chatmessage

### ISSUE THREAD

**Issue by ZoopaMario** [LapisPlugins/AFKPlus#2]
If in afk-state, whenever i write a chatmessage, it isnt displayed in chat, i remain afk, and the console throws out this error: 

```
ERROR Could not pass event AsyncPlayerChatEvent to AFKPlus v3.1.3
INFO java.lang.IllegalStateException: AFKStopEvent may only be triggered synchronously.
INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.2.jar:git-Paper-96]
INFO at net.lapismc.afkplus.playerdata.AFKPlusPlayer.stopAFK(AFKPlusPlayer.java:168) ~[?:?]
INFO at net.lapismc.afkplus.playerdata.AFKPlusPlayer.interact(AFKPlusPlayer.java:217) ~[?:?]
INFO at net.lapismc.afkplus.AFKPlusListeners.onPlayerChat(AFKPlusListeners.java:56) ~[?:?]
INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.2.jar:git-Paper-96]
INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.2.jar:git-Paper-96]
INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-96]
INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-96]
INFO at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1745) ~[patched_1.14.2.jar:git-Paper-96]
INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.14.2.jar:git-Paper-96]
INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.2.jar:git-Paper-96]
INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191] 
INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
Sending a command while afk works as intended without errors.

**Comment by Dart2112** [comment]
[AFKPlus.zip](https://github.com/LapisPlugins/AFKPlus/files/3316873/AFKPlus.zip)
Here, this should fix it

**Comment by ZoopaMario** [comment]
works, thank you ! :)
