### ISSUE TITLE
Fake AFK not working

### ISSUE THREAD

**Issue by TheRealCyber** [LapisPlugins/AFKPlus#44]
I have given all the permissions to the players to use fake afk but every time I run the command it says "You aren't permitted to do this"

I have tried all the commands, "/afk -fake" "/afk:afk -fake"

When I run it through the console I get this error 
```
Unexpected exception while parsing console command "afk:afk -fake"
org.bukkit.command.CommandException: Unhandled exception executing 'afk:afk -fake' in net.lapismc.afkplus.commands.AFK(afk)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1626]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1626]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1626]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1626]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1626]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1626]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1626]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @7aec35a)
at net.lapismc.afkplus.commands.AFK.onCommand(AFK.java:67) ~[AFKPlus.jar:?]
at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.onCommand(LapisCoreCommand.java:190) ~[AFKPlus.jar:?]
at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.execute(LapisCoreCommand.java:178) ~[AFKPlus.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
... 8 more
```

Not sure what the issue is, any help would be appreciated

**Comment by Dart2112** [comment]
Found the issue. it was an order of operations error in the code. 
Should be fixed in the next update that I'm about to push out

**Comment by Dart2112** [comment]
Update pushed out, closing

**Comment by TheRealCyber** [comment]
Awesome! thanks for the quick response and patch!
