### ISSUE TITLE
Unhandled Tab-Completion Exception

### ISSUE THREAD

**Issue by GamerGuyD3** [LapisPlugins/AFKPlus#77]
An error occurs when attempting to type out the command `/afkplus player <player>`.

>version afkplus
[00:09:05] [Server thread/INFO]: AFKPlus version 3.4.5
[00:09:05] [Server thread/INFO]: AFK for professional servers
[00:09:05] [Server thread/INFO]: Author: Dart2112
[00:09:05] [Server thread/INFO]: AFKPlusPrefix version 1.3.5
[00:09:05] [Server thread/INFO]: Author: Dart2112

Console:
`[00:03:30] [Server thread/ERROR]: Exception when TrueProtocol attempted to tab complete afkplus player 
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'afkplus player ' in net.lapismc.afkplus.commands.AFKPlusCmd(afkplus)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:236) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.tabCompleteCommand(CraftServer.java:2223) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.tabComplete(CraftServer.java:2195) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at org.bukkit.craftbukkit.v1_21_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:60) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.3.10.jar:4394-Spigot-60c9969-2b9a094]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:542) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:524) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:745) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:37) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4394-Spigot-60c9969-2b9a094]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "s" is null
        at net.lapismc.afkplus.util.core.commands.tabcomplete.LapisCoreTabCompleter.recursiveSearch(LapisCoreTabCompleter.java:99) ~[?:?]
        at net.lapismc.afkplus.util.core.commands.tabcomplete.LapisCoreTabCompleter.recursiveSearch(LapisCoreTabCompleter.java:106) ~[?:?]
        at net.lapismc.afkplus.util.core.commands.tabcomplete.LapisCoreTabCompleter.onTabComplete(LapisCoreTabCompleter.java:84) ~[?:?]
        at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.tabComplete(LapisCoreCommand.java:220) ~[?:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:232) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 24 more`

**Comment by Dart2112** [comment]
The issue has been auto closed due to the commit
Unfortunately I cannot replicate the error so I cant guarantee that it's fixed.
I can send you a test file if you'd like to test it, or you can test it in the next AFKPlus update
